trigger:
  - master
  - develop

variables:
  buildConfiguration: 'Release'
  cakeVersion: 0.38.5
  sdkVersion: '2.2.300'
  target: NuGet

pool:
  vmImage: 'windows-2019'
steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      packageType: sdk
      version: $(sdkVersion)
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '>=5.x'
  - task: DotNetCoreCLI@2
    displayName: Install Cake tool
    inputs:
      command: custom
      custom: tool
      arguments: install -g Cake.Tool --version $(cakeVersion)
  - task: DotNetCoreCLI@2
    displayName: Run build
    inputs:
      command: custom
      custom: cake
      arguments: --settings_skipverification=true --target=$(target)
  - task: PublishPipelineArtifact@1
    displayName: Publish packages artifact
    inputs:
      path: dist/package
      artifact: package
  - task: PublishPipelineArtifact@1
    displayName: Publish build output
    inputs:
      path: dist/build
      artifact: publish